export const TECHINIQUES = "@get/TECHINIQUES";
export const SPECIFIC_TECHINIQUE = "@get/SPECIFIC_TECHINIQUE";
export const IMAGES = "@get/IMAGES";
export const DATE_IMAGES = "@get/DATE_IMAGES";
export const NEXT_URL = "@get/NEXT_URL";
export const MAX_PAGES = "@get/MAX_PAGES";

export const CLASSIFICATION = "@get/CLASSIFICATION";
export const NEXT_URL_CLASSIFICATION = "@get/NEXT_URL_CLASSIFICATION";
export const IMAGE_BY_CLASSIFICATION = "@get/IMAGE_BY_CLASSIFICATION";
export const SEARCH_CLASSIFICATION = "@get/SEARCH_CLASSIFICATION";
export const MAX_PAGES_CLASSIFICATION = "@get/MAX_PAGES_CLASSIFICATION";
